blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogDetailView

urlpatterns = [
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='detail'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('mailings.urls', 'mailings'), namespace='mailings')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import MailingSettingsDetailView, MailingSettingsListView, MailingSettingsCreateView, \
    MailingSettingsDeleteView, MailingSettingsUpdateView, ClientListView, ClientCreateView, ClientUpdateView, \
    LogListView, ClientDetailView, ClientDeleteView, toggle_activity_mailings

urlpatterns = [
    path('log/', LogListView.as_view(), name='log_list'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('distribution/<int:pk>/', MailingSettingsDetailView.as_view(), name='distribution_detail'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='distribution_delete'),
    path('', MailingSettingsListView.as_view(), name='distribution_list'),
    path('create/', MailingSettingsCreateView.as_view(), name='create_distribution'),
    path('edit/<int:pk>/', MailingSettingsUpdateView.as_view(template_name='mailings/mailingsettings_update_form.html'),
         name='distribution_edit'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='detail_client'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('activity_mailings/<int:pk>/', toggle_activity_mailings, name='toggle_activity_mailings'),
]

mailings/models.py
from django.db import models


from users.models import User

NULLABLE = {'null': True, 'blank': True}

class Client(models.Model):
    """Модель клиента"""
    FIO = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(max_length=150, verbose_name='почта', unique=True)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    owner = models.ForeignKey(User, **NULLABLE, verbose_name='Владелец', help_text='Введите владельца',
                              on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.FIO} {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"
        ordering = ('FIO',)
        permissions = [
            ("can_view_clients", "Может смотреть просматривать клиентов"),
            ("can_change_clients", "Может смотреть изменять клиентов"),
            ("can_delete_clients", "Может удалять Клиентов"),
        ]

class MailingSettings(models.Model):
    """Модель настроек рассылки"""
    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    start_time = models.DateTimeField(verbose_name='время начала рассылки')
    end_time = models.DateTimeField(verbose_name='время окончания рассылки')
    periodicity = models.CharField(max_length=50, verbose_name='периодичность', choices=PERIODICITY_CHOICES)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=CREATED, verbose_name='статус рассылки')

    clients = models.ManyToManyField(Client, verbose_name='клиенты рассылки')
    owner = models.ForeignKey(User, **NULLABLE, verbose_name='Владелец', help_text='Введите владельца',
                              on_delete=models.SET_NULL)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'time: {self.start_time} - {self.end_time}, periodicity: {self.periodicity}, status: {self.status},' \
               f'owner: {self.owner}'

    class Meta:
        verbose_name = 'настройки рассылки'
        verbose_name_plural = 'настройки рассылки'

        permissions = [
            (
                'change_status',
                'Может менять состояние рассылки'
            )
        ]


class Message(models.Model):
    """Модель сообщений"""
    title = models.CharField(max_length=100, verbose_name='тема письма')
    text = models.TextField(verbose_name='тело письма')
    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка',
                                     related_name='messages', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Log(models.Model):
    """Модель логов"""
    time = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    status = models.BooleanField(verbose_name='статус попытки')
    server_response = models.CharField(verbose_name='ответ почтового сервера', **NULLABLE)

    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент рассылки')

    def __str__(self):
        return f'{self.time} {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

class TryMailing(models.Model):
    SUCCESS = "success"
    FAILURE = "failure"
    STATUSES = [(SUCCESS, "success"), (FAILURE, "failure")]
    last_try = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата последней попытки"
    )
    status = models.CharField(choices=STATUSES, default=SUCCESS, verbose_name="Статус")
    response = models.TextField(**NULLABLE, verbose_name="Ответ")
    mailing = models.ForeignKey(
        MailingSettings,
        on_delete=models.CASCADE,
        related_name="logs",
        verbose_name="Рассылка",
    )

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылок"
        ordering = ("status",)

    def __str__(self):
        return f"{self.status}"

mailings/forms.py
from django.forms import ModelForm
from mailings.models import MailingSettings, Message, Log, Client

class StyleFormMixin:
    """Миксин"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingSettingsForm(StyleFormMixin, ModelForm):
    """Форма настроек рассылки"""
    class Meta:
        model = MailingSettings
        fields = ('start_time', 'end_time', 'periodicity', 'status', 'clients',)


class PermMailingSettingsForm(StyleFormMixin, ModelForm):
    """Форма настроек рассылки для тех у кого частичные разрешения"""
    class Meta:
        model = MailingSettings
        fields = ('status', )


class MessageForm(StyleFormMixin, ModelForm):
    """Форма сообщений"""
    class Meta:
        model = Message
        fields = ('title', 'text',)


class ClientForm(StyleFormMixin, ModelForm):
    """Форма клиента"""
    class Meta:
        model = Client
        fields = ('FIO', 'email', 'comment',)

mailings/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.forms import inlineformset_factory
from django.conf import settings
from django.core.cache import cache
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from mailings.models import Client, MailingSettings, Message, Log
from mailings.forms import MessageForm, MailingSettingsForm, ClientForm, PermMailingSettingsForm
from blog.models import Blog

class ClientListView(LoginRequiredMixin, ListView):
    """Список клиентов"""
    model = Client

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Client.objects.all()
        else:
            return Client.objects.filter(owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailings:clients_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Обновление клиента"""
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailings:clients_list')

    def test_func(self):
        client = self.get_object()
        return self.request.user.is_superuser or self.request.user == client.owner


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Просмотр одного клиента"""
    model = Client

    def test_func(self):
        client = self.get_object()
        return self.request.user.is_superuser or self.request.user == client.owner


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    success_url = reverse_lazy('mailings:clients_list')

    def test_func(self):
        client = self.get_object()
        return self.request.user.is_superuser or self.request.user == client.owner


class MailingSettingsDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    """Просмотр одной рассылки"""
    model = MailingSettings

    def test_func(self):
        mailing_settings = self.get_object()
        return (self.request.user.is_superuser or self.request.user == mailing_settings.owner or
                self.request.user.has_perm(
                    'mailings.view_mailingsettings'))


class MailingSettingsListView(LoginRequiredMixin, ListView):
    """Просмотр списка рассылок"""
    model = MailingSettings

    def cache_example(self):
        if settings.CACHE_ENABLE:
            key = f'mailset_list'
            mailset_list = cache.get(key)
            print(mailset_list)
            if mailset_list is None:
                mailset_list = MailingSettings.objects.all()
                cache.set(key, mailset_list)
        else:
            mailset_list = MailingSettings.objects.all()
        return mailset_list

    def get_queryset(self):
        return self.cache_example()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        user = self.request.user
        if user.is_superuser:
            context_data['all'] = MailingSettings.objects.count()
            context_data['active'] = MailingSettings.objects.filter(status=MailingSettings.STARTED).count()
            mailing_list = context_data['object_list']
            clients = [[client.email for client in mailing.clients.all()] for mailing in mailing_list]
            context_data['clients_count'] = len(clients)
        else:
            mailing_list = MailingSettings.objects.filter(owner=user)
            clients = [[client.email for client in mailing.clients.all()] for mailing in mailing_list]
            context_data['all'] = mailing_list.count()
            context_data['active'] = mailing_list.filter(status=MailingSettings.STARTED).count()
            context_data['clients_count'] = len(clients)
        random_blogs = Blog.objects.order_by('?')[:3]
        article_titles = [blog.title for blog in random_blogs]
        article_pk = [blog.pk for blog in random_blogs]
        context_data['articles'] = dict(zip(article_titles, article_pk))
        return context_data


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    """Создание рассылки"""
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailings:distribution_list')

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingSettings, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST)
        else:
            context_data['formset'] = MessageFormset()

        return context_data

    def get_success_url(self):
        return reverse('mailings:distribution_list')


class MailingSettingsDeleteView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, DeleteView):
    """Удаление рассылки"""
    model = MailingSettings
    permission_required = 'mailings.delete_mailingsettings'

    def test_func(self):
        mailing_settings = self.get_object()
        return self.request.user.is_superuser or self.request.user == mailing_settings.owner

    def get_success_url(self):
        return reverse('mailings:distribution_list')


class MailingSettingsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Обновление рассылки"""
    model = MailingSettings
    form_class = MailingSettingsForm

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('mailings.change_status')

    def get_form_class(self):
        if self.request.user.has_perm('mailings.change_status') and not self.request.user.is_superuser:
            return PermMailingSettingsForm
        return MailingSettingsForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingSettings, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailings:distribution_detail', args=[self.object.pk])


class LogListView(LoginRequiredMixin, ListView):
    """Просмотр списка логов"""
    model = Log

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        user = self.request.user
        mailing_list = MailingSettings.objects.filter(owner=user).first()
        if user.is_superuser:
            context_data['all'] = Log.objects.count()
            context_data['success'] = Log.objects.filter(
                status=True).count()
            context_data['error'] = Log.objects.filter(status=False).count()
        else:
            user_logs = Log.objects.filter(mailing_list=mailing_list)
            context_data['all'] = user_logs.count()
            context_data['success'] = user_logs.filter(
                status=True).count()
            context_data['error'] = user_logs.filter(status=False).count()
        return context_data

def toggle_activity_mailings(request, pk):
    mailings = get_object_or_404(MailingSettings, pk=pk)
    if mailings.is_active:
        mailings.is_active = False
    else:
        mailings.is_active = True

    mailings.save()

    return redirect(reverse('mailings:distribution_list'))

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

</head>
{% include 'includes/inc_main_menu.html' %}

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
    <div class="row">
        <div class="col-12 col-md">
            Рассылки
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {% if object.owner == request.user or request.user.is_superuser %}
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента №{{ object.pk }}?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailings:clients_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/client_detail.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="col-12">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-3">Клиент {{ object.pk }}</h3>
        <p class="lead">Подробное описание клиента</p>
    </div>
</div>

{% if object.owner == request.user or request.user.is_superuser %}
<div class="col-12 text-center">
    <table class="table table-striped">
        <tr>
            <th>ФИО клиента</th>
            <th>Email клиента</th>
            <th>Комментарий</th>
            <th>Владелец</th>
        </tr>
        <tr>
            <td><h4>{{ object.FIO }}</h4></td>
            <td><h4>{{ object.email }}</h4></td>
            <td><h4>{{ object.comment }}</h4></td>
            <td><h4>{{ object.owner }}</h4></td>
        </tr>
    </table>
    <div align="center"><a class="btn btn-outline-primary btn-lg" href="{% url 'mailings:clients_list' %}">Вернуться
        на главную страницу</a></div>
    {% endif %}
</div>
    {% endblock %}

mailings/templates/mailings/client_form.html
{% extends "mailings/base.html" %}
{% block content %}
<form method="post" class="row">
    {% csrf_token %}
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3>Настройки рассылки</h3>
            </div>
            <div class="card-body">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'mailings:clients_list' %}" class="btn btn-warning">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

mailings/templates/mailings/client_list.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-3">Список имеющихся клиентов</h3>
</div>


<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Клиенты</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">

                    <tr>
                        <th><h6>ФИО клиента</h6></th>
                        <th><h6>email клиента</h6></th>
                        <th><h6>Комментарий</h6></th>
                        <th><h6>Исправить данные</h6></th>
                        <th><h6>Перейти к клиенту</h6></th>
                        <th><h6>Удалить клиента</h6></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h6>{{ object.FIO }}</h6></td>
                        <td><h6>{{ object.email }}</h6></td>
                        <td><h6>{{ object.comment }}</h6></td>

                        <td><h6><a class="btn btn-lg btn-warning"
                                   href="{% url 'mailings:edit_client' object.pk %}">Исправить</a></h6></td>
                        <td><h6><a class="btn btn-lg btn-success"
                                   href="{% url 'mailings:detail_client' object.pk %}">Перейти</a></h6></td>
                        <td><h6><a class="btn btn-lg btn-danger"
                                   href="{% url 'mailings:delete_client' object.pk %}">Удалить</a></h6></td>

                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary btn-block btn-lg" href="{% url 'mailings:create_client' %}">Создать
                нового клиента</a>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/clients_list.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-3">Список имеющихся клиентов</h3>
</div>


<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Клиенты</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">

                    <tr>
                        <th><h6>ФИО клиента</h6></th>
                        <th><h6>email клиента</h6></th>
                        <th><h6>Комментарий</h6></th>
                        <th><h6>Исправить данные</h6></th>
                        <th><h6>Перейти к клиенту</h6></th>
                        <th><h6>Удалить клиента</h6></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h6>{{ object.FIO }}</h6></td>
                        <td><h6>{{ object.email }}</h6></td>
                        <td><h6>{{ object.comment }}</h6></td>

                        <td><h6><a class="btn btn-lg btn-warning"
                                   href="{% url 'mailings:edit_client' object.pk %}">Исправить</a></h6></td>
                        <td><h6><a class="btn btn-lg btn-success"
                                   href="{% url 'mailings:detail_client' object.pk %}">Перейти</a></h6></td>
                        <td><h6><a class="btn btn-lg btn-danger"
                                   href="{% url 'mailings:delete_client' object.pk %}">Удалить</a></h6></td>

                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary btn-block btn-lg" href="{% url 'mailings:create_client' %}">Создать
                нового клиента</a>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/log_list.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-3">Лог рассылок</h3>
</div>

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <tr>
                            <th><h4>Количество отправленных писем</h4></th>
                            <th><h4>Количество успешно отправленных писем</h4></th>
                            <th><h4>Количество ошибок</h4></th>
                        </tr>
                        <body>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ success }}</h4></td>
                            <td><h4>{{ error }}</h4></td>
                        </tr>
                        </body>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">
                    <tr>
                        <th><h4>Время рассылки</h4></th>
                        <th><h4>Данные рассылки</h4></th>
                        <th><h4>Получатель рассылки</h4></th>
                        <th><h4>Статус рассылки</h4></th>
                    </tr>
                    {% for object in object_list %}
                    {% if object.mailing_list.owner == request.user or request.user.is_superuser %}
                    <tr>
                        <td><h4>{{ object.time }}</h4></td>
                        <td><h4>{{ object.mailing_list }}</h4></td>
                        <td><h4>{{ object.client }}</h4></td>
                        <td>
                            <h4>
                                {% if object.status %}
                                <p style="color:green">Успешно</p>
                                {% else %}
                                <p style="color:red">Ошибка</p>
                                {% endif %}
                            </h4>
                        </td>
                        {% endif %}
                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingsettings_list.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h3 class="display-3">Страница контроля рассылок</h3>
</div>

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <tr>
                            <th><h4>Количество рассылок</h4></th>
                            <th><h4>Количество активных рассылок</h4></th>
                            <th><h4>Количество уникальных клиентов</h4></th>
                        </tr>
                        <body>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ active }}</h4></td>
                            <td><h4>{{ clients_count }}</h4></td>
                        </tr>
                        </body>
                    </table>
                    <hr>
                    <table class="table">
                        <tr>
                            <h3>Случайные статьи</h3>
                            <th><h5>Статьи</h5></th>
                            <th><h5>Подробнее</h5></th>
                        </tr>
                        <tbody>
                        {% for article, pk in articles.items %}
                        <tr>
                            <td><h5>{{ article }}</h5></td>
                            <td><a class="p-2 btn btn-primary"
                                   href="{% url 'blog:detail' pk %}">Перейти к статье</a>
                            </td>
                            {% endfor %}
                        </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-12">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12 text-center">
                <table class="table">
                    <tr>

                        <th><h6>Время рассылки</h6></th>
                        <th><h6>Статус рассылки</h6></th>
                        <th><h6>Периодичность рассылки</h6></th>
                        <th><h6>Владелец рассылки</h6></th>
                        <th><h6>Подробности рассылки</h6></th>

                        <th><h6>Редактирование рассылки</h6></th>


                        <th><h6>Удаление рассылки</h6></th>

                        <th><h6>Активность рассылки</h6></th>

                    </tr>
                    {% for object in object_list %}

                    <tr>
                        <td><h6>{{ object.start_time }}</h6></td>
                        <td><h6>{{ object.status }}</h6></td>
                        <td><h6>{{ object.periodicity }}</h6></td>
                        <th><h6>{{ object.owner }}</h6></th>
                        {% if object.is_active %}
                        <th><h6>Активна</h6></th>
                        {% else %}
                        <th><h6>Отменена</h6></th>
                        {% endif %}
                        <td><h6>
                            <a href="{% url 'mailings:distribution_detail' object.pk %}"
                               class="btn btn-lg btn-primary">Полная
                                информация</a>
                        </h6></td>
                        <td><h6>
                            {% if user.is_superuser %}
                            <a class="btn btn-lg btn-warning"
                               href="{% url 'mailings:distribution_edit' object.pk %}">Исправить</a>
                            {% endif %}
                        </h6></td>
                        <td><h6>
                            {% if object.is_active %}
                            <a class="btn btn-danger" href="{% url 'mailings:toggle_activity_mailings' object.pk%}">Отменить</a>
                            {% else %}
                            <a class="btn btn-success" href="{% url 'mailings:toggle_activity_mailings' object.pk%}">Активировать</a>
                            {% endif %}
                        </h6></td>


                        {% endfor %}

                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary btn-block btn-lg" href="{% url 'mailings:create_distribution' %}">Создать
                новую рассылку</a>
        </div>
    </div>
</div>
{% endblock %}