blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogDetailView

urlpatterns = [
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='detail'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('mailings.urls', 'mailings'), namespace='mailings')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import MailingSettingsDetailView, MailingSettingsListView, MailingSettingsCreateView, \
    MailingSettingsDeleteView, MailingSettingsUpdateView, ClientListView, ClientCreateView, ClientUpdateView, \
    LogListView, ClientDetailView, ClientDeleteView, toggle_activity_mailings

urlpatterns = [
    path('log/', LogListView.as_view(), name='log_list'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('distribution/<int:pk>/', MailingSettingsDetailView.as_view(), name='distribution_detail'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='distribution_delete'),
    path('', MailingSettingsListView.as_view(), name='distribution_list'),
    path('create/', MailingSettingsCreateView.as_view(), name='create_distribution'),
    path('edit/<int:pk>/', MailingSettingsUpdateView.as_view(template_name='mailings/mailingsettings_update_form.html'),
         name='distribution_edit'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='detail_client'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('activity_mailings/<int:pk>/', toggle_activity_mailings, name='toggle_activity_mailings'),
]

blog/models.py
from django.db import models

from mailings.models import NULLABLE


class Blog(models.Model):
    """Модель блога"""
    title = models.CharField(max_length=50, verbose_name='заголовок')
    text = models.TextField(verbose_name='текст')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    count_of_view = models.IntegerField(default=0, verbose_name='Просмотры')
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')

    def __str__(self):
        return f'{self.title} {self.count_of_view}'

blog/views.py
from django.views.generic import DetailView

from blog.models import Blog


class BlogDetailView(DetailView):
    """Конкретный блог"""
    model = Blog

    def get(self, request, *args, **kwargs):
        article = self.get_object()

        article.count_of_view += 1
        article.save()

        return super().get(request, *args, **kwargs)

blog/templates/blog/blog_detail.html
{% extends "mailings/base.html" %}
{% block content %}
<div class="col-12">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h3 class="display-3">Блог {{ object.title }}</h3>
    </div>
</div>

<div class="col-12 text-center">
    <table class="table table-striped">
        <tr>
            <th>Заголовок</th>
            <th>Текст</th>
            <th>Изображение</th>
            <th>Просмотры</th>
            <th>Дата публикации</th>
        </tr>
        <tr>
            <td><p>{{ object.title }}</p></td>
            <td>
                <div style="max-width: 400px; word-wrap: break-word;">{{ object.text }}</div>
            </td>
            {% if object.image %}
            <td>
                <img class="card-img-top" style="max-width: 500px; max-height: 500px;" src="{{ object.image.url }}"
                     alt="Изображение">
            </td>
            {% else %}
            <td>
                <p>Изображение отсутствует</p>
            </td>
            {% endif %}
            <td><p>{{ object.count_of_view }}</p></td>
            <td><p>{{ object.date }}</p></td>
        </tr>
    </table>
    <div align="center"><a class="btn btn-outline-primary btn-lg" href="{% url 'mailings:clients_list' %}">Вернуться
        на главную страницу</a>
    </div>
</div>
    {% endblock %}