blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogDetailView

urlpatterns = [
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='detail'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('mailings.urls', 'mailings'), namespace='mailings')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import logout_view, RegisterView, ProfileView, email_verification, recovery_password, UserListView, UserDetailView, UserUpdateView, UserDeleteView


app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path('recovery/', recovery_password, name='recovery'),

    path('users/', UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/view', UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/delete/', UserDeleteView.as_view(), name='user_delete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"null": True, "blank": True}


class User(AbstractUser):
    """ Класс для модели пользователей """
    username = None
    email = models.EmailField(unique=True, verbose_name="Почта", help_text="Укажите почту")

    avatar = models.ImageField(upload_to="users/avatars/", verbose_name="Фото", **NULLABLE, help_text="Загрузите фото")
    phone = models.CharField(max_length=35, verbose_name="Телефон", help_text="Введите номер телефона", **NULLABLE)
    country = models.CharField(max_length=50, verbose_name="Страна", help_text="Введите страну", **NULLABLE)

    token = models.CharField(max_length=100, verbose_name="Токен", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        """ Строковое представление данных """
        return f'{self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = "Пользователи"
        # Прописываем кастомные права пользователя
        permissions =[
            ("Can_edit_is_active", "Can edit is active"),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from mailings.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, ModelForm):
    class Meta:
        model = User
        fields = '__all__'


class UserManagerForm(StyleFormMixin, ModelForm):
    """ Прописываем форму для кастомных прав доступа """
    class Meta:
        model = User
        fields = ('is_active',)


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        """ Что бы скрыть в форме "Пароль не задан" """
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth import logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group

from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from config.settings import EMAIL_HOST_USER
from users.forms import UserProfileForm, UserRegisterForm, UserManagerForm
from users.models import User


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'


class UserDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = User
    permission_required = 'users.view_user'


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        # Присваиваем пользователю группу Пользователи
        user.groups.add(Group.objects.get(name='Пользователь'))
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject="Подтверждение почты",
            message=f"Перейти по ссылке для подтверждения почты: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)

def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def recovery_password(request):
    if request.method == "POST":
        email = request.POST.get('email')
        token = secrets.token_hex(8)

        user_recovery_password = get_object_or_404(User, email=email)
        user_recovery_password.password = make_password(token)
        user_recovery_password.save()
        send_mail(
                  subject="Смена пароля",
                  message=f"Автоматически сформированный пароль: {token}",
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[email]
                )
    return render(request, 'users/user_password_reset.html')


class ProfileView(LoginRequiredMixin,UpdateView):
    model = User
    form_class = UserProfileForm
    # permission_required = 'users.change_profile'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def logout_view(request):
    logout(request)
    return redirect('/')


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserManagerForm
    permission_required = 'users.change_user'
    success_url = reverse_lazy('users:user_list', )


class UserDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = User
    permission_required = 'users:delete_user'
    success_url = reverse_lazy('users:user_list')

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:recovery' %}" class="btn btn-danger">Забыли пароль? Заведем новый</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}

{% block content %}
{% if perms.users.view_user %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header text-center">
                <h4>Пользователи</h4>
            </div>
            <div class="card-body">
                {% for object in object_list %}
                {% if not object.is_superuser and request.user != object %}
                <div class="d-flex align-items-center justify-content-between" style="margin-bottom: 10px;">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                    <a href="{% url 'users:user_update' object.pk  %}" type="button"
                       class="btn btn-danger">Изменить активность</a>
                </div>
                <hr>
                {% endif %}
                {% endfor %}
            </div>

            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <div class="card-title nth-card-title">
                    <h4>Запрос на восстановление пароля на сайте</h4>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-danger mt-2">Восстановить пароль</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_sent.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <h4 class="alert-heading">Письмо с новым паролем отправлено!</h4>
                <p>
                    На ваш адрес электронной почты было отправлено письмо с новым паролем.
                </p>
            </div>
            <div class="card-footer"><a href="{% url 'users:login' %}" class="btn btn-danger">К форме авторизации</a></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_update.html
{% extends 'mailings/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Профиль пользователя {{ object.email }}
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}